<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b231915b-dd77-4c04-b388-91a9384043ee</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Velonixs.Connect.Application\Velonixs.Connect.Application.csproj" />
    <ProjectReference Include="..\Velonixs.Connect.Infrastructure\Velonixs.Connect.Infrastructure.csproj" />
    <ProjectReference Include="..\Velonixs.Connect.Persistence\Velonixs.Connect.Persistence.csproj" />
  </ItemGroup>

</Project>
